library 'pipe@master' //
def preCommands = "echo 1"
def postCommands = "echo 2"

def jobInfo = [
    nodeName: "master",
    projName: "gateway",
    name: "appdc",
    appName: "appdc",
    buildInfo: [ //
        pom: "pom.xml", //
        mode: "deploy",
        options: "-DskipTests" // 
    ],
 packageInfo: [ //打包信息
        name: "appdc", //
        packageName: "appdc" //
    deployInfo: [ //
        DEV:[ //'master'
            [
                hostName: "dev-java-gateway01",
                packageFile: "*-DEV*.tar.gz",
                targetFolder: "/tmp",
                preCommands: "bash pwd", //
                postCommands: postCommands //
            ]
        ],
        QA:[ //'rel_'
            [
                hostName: "dev-192.168.168.7", //
                packageFile: "*-QA*.tar.gz", //
                targetFolder: ".", //
                preCommands: preCommands, //
                postCommands: postCommands //
            ]
        ] 
    ],
     releaseInfo: [ 
	 serverName: "artifactory", //
      packages: [
		[ //
        fileName: "*-PRD*.tar.gz", //
        serverName: "artifactory", //
        repoName: "generic-release", //
        projectName: "erp", //
        packageName: "custodianerp", //
        props: "proj=erp" //
    ] 
      ]
    ]
]

building.buildJavaService(jobInfo) //
